### ISSUE TITLE
上电后，在不断电情况下，从AP模式转换到STA模式。并且连接AP后，无法显示IP,急急急！！

### ISSUE THREAD

**Issue by spanking123** [sj15712795029/stm32f1_marvell88w8801_marvell8801_wifi#12]
问题很急，麻烦大神快点支援一下，万分感谢

**Comment by sj15712795029** [comment]
修改：
case HOST_CMD_APCMD_BSS_STOP:
    {
        pmrvl88w8801_core->bss_type = BSS_TYPE_STA;
        ethernet_dhcpd_stop();
        break;
    }
